### ISSUE TITLE
Downgrades are being proposed

### ISSUE THREAD

**Issue by FriedrichFroebel** [saadmk11/github-actions-version-updater#20]
There seems to be something off with resolving the actual version changes:

```
Found new version for "actions/checkout"
  Updating "actions/checkout@v3" with "actions/checkout@v2.5.0"
  Found new version for "saadmk11/github-actions-version-updater"
  Updating "saadmk11/github-actions-version-updater@main" with "saadmk11/github-actions-version-updater@v0.5.6"
  Found new version for "actions/setup-python"
  Updating "actions/setup-python@v4" with "actions/setup-python@v4.3.0"
```

The specific issues I see here:

* `v2.5.0` is considered more recent than version `v3` for `actions/checkout`.
* `v0.5.6` is considered more recent than `main`, although `main` references the latest unreleased code from the default branch.
* `v4.3.0` is being proposed for the short syntax `v4`, although I would assume that `v4` will always use the latest release of the `v4` major version (currently being `v4.3.0` for `actions/setup-python`). I am not sure about this though, as I could not find any information on which version is being picked by GitHub Actions in this case.

**Comment by saadmk11** [comment]
Hi @FriedrichFroebel, Thanks for reporting this issue.


> * `v2.5.0` is considered more recent than version `v3` for `actions/checkout`.

This is a known problem. This is happening because this action uses [GitHub's Latest Release API](https://docs.github.com/en/rest/releases/releases#get-the-latest-release) which returns the Latest Release Published by the repository, which sometimes may not be the latest version available for the action (e.g: if the repository is maintaining multiple versions at the same time `v2.x`, `v3.x` and a new version of `v2.x` is released)

> * `v0.5.6` is considered more recent than `main`, although `main` references the latest unreleased code from the default branch.

The Action Currently Supports Tags Only (will support commit SHA (from default branch or latest release Tag) in the near future. https://github.com/saadmk11/github-actions-version-updater/pull/19). There is no plan for suggesting branches.

> * `v4.3.0` is being proposed for the short syntax `v4`, although I would assume that `v4` will always use the latest release of the `v4` major version (currently being `v4.3.0` for `actions/setup-python`). I am not sure about this though, as I could not find any information on which version is being picked by GitHub Actions in this case.

This behavior is intentional. This Action will not suggest moving versions rather it will suggest specific versions.

**Comment by FriedrichFroebel** [comment]
Thanks for the explanations. In my opinion, these limits should be mentioned somewhere in the docs as well, as otherwise one will just stumble upon them when actually trying to use them.

**Comment by saadmk11** [comment]
> > * `v2.5.0` is considered more recent than version `v3` for `actions/checkout`.
> 
> This is a known problem. This is happening because this action uses [GitHub's Latest Release API](https://docs.github.com/en/rest/releases/releases#get-the-latest-release) which returns the Latest Release Published by the repository, which sometimes may not be the latest version available for the action (e.g: if the repository is maintaining multiple versions at the same time `v2.x`, `v3.x` and a new version of `v2.x` is released)

Fixed on https://github.com/saadmk11/github-actions-version-updater/pull/19

**Comment by SebastianStehle** [comment]
Awesome, thanks a lot :)
